name: Build and Test Multi-Web Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t multi-web-container .

      - name: Run Docker container
        run: |
          docker network create my-network
          docker run -d --name multi-web-container --network my-network -p 80:80 -p 8080:8080 multi-web-container

      - name: Wait for services to start
        run: sleep 10

      - name: Check Status of Supervisord
        run: docker exec multi-web-container supervisorctl status
        continue-on-error: true

      - name: Read apache2 log files
        run: |
          cat /var/log/apache2/error.log
          echo ""
          echo ""
          echo ""
          cat /var/log/apache2/other_vhosts_access.log
        continue-on-error: true
        
      - name: Curl Apache
        run: |
          docker run --rm --network my-network curlimages/curl:latest curl http://multi-web-container:8080
        continue-on-error: true

      - name: Curl Nginx
        run: |
          docker run --rm --network my-network curlimages/curl:latest curl http://multi-web-container:80
        continue-on-error: true

      - name: Stop and remove Docker container
        run: |
          docker stop multi-web-container
          docker rm multi-web-container
          docker network rm my-network
